apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sparrow-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - sparrow.com
    secretName: aks-ingress-dev-tls
  rules:
  - host: sparrow.com
    http:
      paths:   
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: sparrowgateway-service
            port:
              number: 8090
      - path: /swagger/
        pathType: Prefix
        backend:
          service:
            name: sparrowgateway-service
            port:
              number: 8090
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sparrow-portal-service
            port:
              number: 80
      - path: /spa/
        pathType: Prefix
        backend:
          service:
            name: sparrow-portal-service-sinoage
            port:
              number: 80